consul:
  host: consul-server
  port: 8500
service:
  discoveryHost: public-gateway
  healthCheck:
    timeout: 1s
    interval: 10s
  maxRetry: 5
  retryInterval: 5000
  id: null
  name: public-gateway
  port: 3000
config:
  name: public-gateway
logger:
  level: info
  transports:
    - transport: console
      colorize: true
      datePattern: YYYY-MM-DD h:mm:ss
      label: public-gateway
    - transport: file
      name: info
      json: false
      filename: ../logs/all.log
      datePattern: YYYY-MM-DD h:mm:ss
      label: public-gateway
      # 200M
      maxsize: 209715200
      maxFiles: 10
    - transport: file
      name: error
      level: error
      json: false
      filename: ../logs/error.log
      datePattern: YYYY-MM-DD h:mm:ss
      label: public-gateway
      # 200M
      maxsize: 209715200
      maxFiles: 10
